import sharp from "sharp";
import { readdir, writeFile } from "fs/promises";
import path from "path";

const imagesDir = "./public/images";
const files = await readdir(imagesDir);
const blurs = {};

for (const f of files) {
  if (!f.endsWith(".jpg") && !f.endsWith(".png")) continue;
  const buf = await sharp(path.join(imagesDir, f))
    .resize(10)
    .blur()
    .webp()
    .toBuffer();
  blurs[f] = `data:image/webp;base64,${buf.toString("base64")}`;
}

const output = `// Auto-generated by scripts/gen-blur.mjs
export const blurDataURLs: Record<string, string> = ${JSON.stringify(blurs, null, 2)};
`;

await writeFile("./src/data/blur-data.ts", output);
console.log(`Generated blur data for ${Object.keys(blurs).length} images.`);
